//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oct12thMVCCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Zones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_Zones()
        {
            this.CMS_Contents = new HashSet<CMS_Contents>();
        }
    
        public int Zone_ID { get; set; }
        public string Zone_Name { get; set; }
        public Nullable<int> Zone_ParentID { get; set; }
        public Nullable<int> Zone_Priority { get; set; }
        public Nullable<int> Zone_Type { get; set; }
        public string Zone_Alias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_Contents> CMS_Contents { get; set; }
    }
}
