//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oct12thMVCCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Contents
    {
        public int Content_ID { get; set; }
        public string Content_Headline { get; set; }
        public string Content_Teaser { get; set; }
        public string Content_Body { get; set; }
        public string Content_Avatar { get; set; }
        public Nullable<System.DateTime> Content_CreateDate { get; set; }
        public Nullable<System.DateTime> Content_ModifiedDate { get; set; }
        public Nullable<int> Content_Status { get; set; }
        public int Content_ZoneID { get; set; }
        public string Content_UserID { get; set; }
        public Nullable<int> Content_ModifiedUserID { get; set; }
        public string Content_Comment { get; set; }
        public Nullable<bool> Content_IsFocus { get; set; }
        public Nullable<bool> Content_IsHot { get; set; }
        public Nullable<int> Content_LgID { get; set; }
        public Nullable<int> Content_Viewed { get; set; }
        public Nullable<int> Content_FocusID { get; set; }
    
        public virtual CMS_Zones CMS_Zones { get; set; }
    }
}
